import io
import os
from contextlib import asynccontextmanager

import numpy as np
import soundfile as sf
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, Response
from pydantic import BaseModel, Field

SAMPLE_RATE = 24000  # Kokoro outputs 24 kHz
_pipelines = {}


def get_pipeline(lang_code: str):
    # 'a' = American English, 'z' = Mandarin
    if lang_code not in _pipelines:
        from kokoro import KPipeline  # lazy import so CI tests don't need the model
        _pipelines[lang_code] = KPipeline(lang_code=lang_code)
    return _pipelines[lang_code]


@asynccontextmanager
async def lifespan(app: FastAPI):
    if not os.environ.get("SKIP_MODEL_LOAD"):
        get_pipeline("a")  # warm English pipeline; health check passing == model ready
    yield


app = FastAPI(title="Kokoro TTS Demo", lifespan=lifespan)


class SynthRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=1000)
    voice: str = "af_heart"
    lang: str = Field("a", pattern="^[az]$")
    speed: float = Field(1.0, ge=0.5, le=2.0)


@app.get("/health")
def health():
    return {"status": "ok"}


def _tts_wav(text: str, voice: str, lang: str, speed: float) -> bytes:
    pipe = get_pipeline(lang)
    chunks = []
    for _graphemes, _phonemes, audio in pipe(text, voice=voice, speed=speed):
        chunks.append(audio.numpy() if hasattr(audio, "numpy") else np.asarray(audio))
    if not chunks:
        raise HTTPException(400, "no audio generated")
    buf = io.BytesIO()
    sf.write(buf, np.concatenate(chunks), SAMPLE_RATE, format="WAV")
    return buf.getvalue()


@app.post("/synthesize")
def synthesize(req: SynthRequest):
    return Response(_tts_wav(req.text, req.voice, req.lang, req.speed),
                    media_type="audio/wav")


# ---------- Phase 3: avatar pipeline (TTS -> SQS -> GPU worker -> MP4) ----------
class AvatarRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=500)
    voice: str = "af_heart"
    lang: str = Field("a", pattern="^[az]$")
    speed: float = Field(1.0, ge=0.5, le=2.0)
    image_key: str | None = None  # portrait object key in the avatar bucket


def _avatar_cfg():
    cfg = {k: os.environ.get(k)
           for k in ("AVATAR_BUCKET", "AVATAR_QUEUE_URL", "AVATAR_TABLE")}
    if not all(cfg.values()):
        raise HTTPException(
            503, "avatar pipeline not deployed (deploy AvatarStack and set AVATAR_* env)")
    return cfg


@app.post("/avatar")
def create_avatar(req: AvatarRequest):
    cfg = _avatar_cfg()
    import json
    import uuid

    import boto3

    job_id = uuid.uuid4().hex[:12]
    wav = _tts_wav(req.text, req.voice, req.lang, req.speed)
    audio_key = f"jobs/{job_id}/speech.wav"
    boto3.client("s3").put_object(Bucket=cfg["AVATAR_BUCKET"], Key=audio_key, Body=wav)
    image_key = req.image_key or os.environ.get(
        "AVATAR_DEFAULT_IMAGE_KEY", "portraits/default.jpg")
    boto3.resource("dynamodb").Table(cfg["AVATAR_TABLE"]).put_item(
        Item={"job_id": job_id, "status": "queued"})
    boto3.client("sqs").send_message(
        QueueUrl=cfg["AVATAR_QUEUE_URL"],
        MessageBody=json.dumps(
            {"job_id": job_id, "audio_key": audio_key, "image_key": image_key}),
    )
    return {"job_id": job_id, "status": "queued"}


@app.get("/avatar/{job_id}")
def avatar_status(job_id: str):
    cfg = _avatar_cfg()
    import boto3

    item = boto3.resource("dynamodb").Table(cfg["AVATAR_TABLE"]).get_item(
        Key={"job_id": job_id}).get("Item")
    if not item:
        raise HTTPException(404, "job not found")
    out = {"job_id": job_id, "status": item["status"]}
    if item.get("video_key"):
        out["video_url"] = boto3.client("s3").generate_presigned_url(
            "get_object",
            Params={"Bucket": cfg["AVATAR_BUCKET"], "Key": item["video_key"]},
            ExpiresIn=3600,
        )
    if item.get("error"):
        out["error"] = item["error"]
    return out


@app.get("/", response_class=HTMLResponse)
def index():
    return """<!doctype html>
<html><head><meta charset="utf-8"><title>Kokoro TTS Demo</title>
<style>body{font-family:sans-serif;max-width:640px;margin:40px auto;padding:0 16px}
textarea{width:100%;height:100px;font-size:15px}button{padding:8px 24px;font-size:15px}</style>
</head><body>
<h2>Kokoro TTS &mdash; AWS Fargate + CDK Demo</h2>
<textarea id="t">Hello! This speech is generated by Kokoro running on AWS Fargate, deployed with CDK.</textarea>
<p><select id="v">
<option value="af_heart">af_heart (English, female)</option>
<option value="am_adam">am_adam (English, male)</option>
<option value="zf_xiaobei">zf_xiaobei (Mandarin, female)</option>
<option value="zm_yunjian">zm_yunjian (Mandarin, male)</option>
</select>
<button onclick="go()">Synthesize</button></p>
<audio id="a" controls></audio>
<script>
async function go(){
  const voice = document.getElementById("v").value;
  const r = await fetch("/synthesize", {method:"POST",
    headers:{"Content-Type":"application/json"},
    body: JSON.stringify({text: document.getElementById("t").value,
                          voice: voice, lang: voice[0]==="z" ? "z" : "a"})});
  if(!r.ok){ alert("error " + r.status); return; }
  const a = document.getElementById("a");
  a.src = URL.createObjectURL(await r.blob());
  a.play();
}
</script></body></html>"""
